ALTER TABLE expenses ADD COLUMN tax DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE expenses ADD COLUMN cgst DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE expenses ADD COLUMN sgst DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE expenses ADD COLUMN service_charge DECIMAL(10, 2) DEFAULT 0;
